#!/bin/sh

hd350bt="HD 350BT"
budspro="Galaxy Buds Pro"

device_list=$(bluetoothctl paired-devices)

connect() {
    for device_name in "$@"
    do
        mac=$(echo "$device_list" | grep -i "$device_name" | awk '{print $2}')
        bluetoothctl connect "$mac"
    done
}

if [ $# -gt 0 ];
then
    connect $@
else
    connect $hd350bt $budspro
fi

